name: HCGradingSupport
main: jp.haruserver.mc.hcgradingsupport.HCGradingSupport
version: 1.1.0
api-version: 1.19
depend: [Vault]
commands:
  hcgs:
    description:
    permission: hcgs.use
    permission-message: 権限 <permission> がありません
